#cloud-config
autoinstall:
    version: 1
    identity:
        realname: 'Vinicius Mascarenhas'
        hostname: meu-ubuntu
        username: tmvinicius
        password: '$y$j9T$uhkxlm8nUQaNu.6rl4k2d.$DIldpYy96OHg8lFjfXfc671BZcGWkPOmaDONGAhGSg3'
    locale: pt_BR.utf8
    keyboard:
        layout: br
    timezone: "America/Sao_Paulo"   
    packages:
        - gimp
        - git
        - wgets
        - docker.io
        - openjdk-17-jdk
        - unzip
    snaps:
        - name: intellij-idea-community
          channel: stable
          classic: true
        - name: brave
          channel: stable
          classic: true
        - name: dbeaver-ce
          channel: stable
          classic: true
        - name: maven
          channel: 3.9.9/stable
          classic: true
        - name: postman
          channel: stable
          classic: true
    codecs:
        install: true
    drivers:
        install: true
    updates: all
    shutdown: reboot

